args <- commandArgs(TRUE)
setwd(".")
a <- as.numeric(args[1])
b <- as.numeric(args[2])
c <- as.numeric(args[3])
d <- as.numeric(args[4])
res <- paste(fisher.test(cbind(c(d,c),c(b,a)))$p.value, a, b, c, d, sep='\t')
cat(res)
