args <- commandArgs(TRUE)
setwd(".")
a <- as.numeric(args[1])
b <- as.numeric(args[2])
c <- as.numeric(args[3])
d <- as.numeric(args[4])
res <- paste( a, b, c, d, fisher.test(cbind(c(d,c),c(b,a)), alternative="g")$p.value, sep='\t')
cat(res)
