source("/home/marco/Downloads/gProfileR/R/gProfileR.R")
args <- commandArgs(TRUE)
query<-read.table(args[1])
back<-read.table(args[2])
res<-gprofiler(query, organism="moryzae", ordered_query=args[3], custom_bg=c(back))
write.table(res, file=paste(file=args[1], "_go_enrich.tsv", sep=""), sep="\t")
