args <- commandArgs(TRUE)
suppressMessages(library(DESeq))
setwd(".")
c1<-read.table( "_out1",row.names=1) 
c2<-read.table( "_out2",row.names=1)
c3<-read.table( "_out3",row.names=1)
c4<-read.table( "_out4",row.names=1)
c5<-read.table( "_out5",row.names=1)
c6<-read.table( "_out6",row.names=1)
counts<-cbind(c1,c2,c3,c4,c5,c6)
colnames(counts)<-c("a1", "a2", "a3", "b1", "b2", "b3")
design <- rep (c("a","b"),each=3)
cds  <-  newCountDataSet(counts, design)
cds  <-  estimateSizeFactors( cds)
cds <- estimateDispersions( cds,fitType="local" )
res  <-  nbinomTest(  cds,  "a",  "b")
resSig <- res[ res$pval < 0.05, ]
write.csv(resSig, file = args[1],  row.names=F, quote=FALSE)